# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpperComputer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 767)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 921, 61))
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 48, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(390, 20, 48, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(460, 20, 131, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 131, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 20, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setEnabled(False)
        self.pushButton_18.setGeometry(QtCore.QRect(720, 20, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 90, 321, 631))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 271, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 340, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 420, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 510, 54, 12))
        self.label_9.setObjectName("label_9")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 100, 231, 22))
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 190, 51, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setEnabled(False)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(80, 200, 231, 22))
        self.horizontalSlider_2.setMaximum(180)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 280, 51, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_3.setEnabled(False)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(80, 290, 231, 22))
        self.horizontalSlider_3.setMaximum(180)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 370, 51, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_4.setEnabled(False)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(80, 380, 231, 22))
        self.horizontalSlider_4.setMaximum(180)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 450, 51, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_5.setEnabled(False)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(80, 460, 231, 22))
        self.horizontalSlider_5.setMaximum(180)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 540, 51, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_6.setEnabled(False)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(80, 550, 231, 22))
        self.horizontalSlider_6.setMaximum(180)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.textEdit_10 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 90, 51, 41))
        self.textEdit_10.setObjectName("textEdit_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 90, 711, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 391, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 50, 111, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 120, 111, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 50, 111, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 50, 111, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 50, 91, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 120, 111, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 120, 111, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 290, 711, 431))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 300, 91, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setGeometry(QtCore.QRect(230, 300, 91, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setGeometry(QtCore.QRect(570, 300, 121, 51))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_14.setEnabled(False)
        self.pushButton_14.setGeometry(QtCore.QRect(40, 370, 91, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setEnabled(False)
        self.pushButton_16.setGeometry(QtCore.QRect(230, 370, 91, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setGeometry(QtCore.QRect(570, 370, 121, 51))
        self.pushButton_17.setObjectName("pushButton_17")
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_7.setGeometry(QtCore.QRect(30, 20, 661, 261))
        self.textEdit_7.setObjectName("textEdit_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setEnabled(False)
        self.pushButton_12.setGeometry(QtCore.QRect(400, 300, 91, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_15.setEnabled(False)
        self.pushButton_15.setGeometry(QtCore.QRect(400, 370, 91, 51))
        self.pushButton_15.setObjectName("pushButton_15")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setEnabled(True)
        self.textEdit_8.setGeometry(QtCore.QRect(1100, 100, 231, 291))
        self.textEdit_8.setMouseTracking(False)
        self.textEdit_8.setTabletTracking(False)
        self.textEdit_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_8.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_8.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textEdit_8.setTabChangesFocus(False)
        self.textEdit_8.setOverwriteMode(False)
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(1100, 470, 231, 181))
        self.textEdit_9.setObjectName("textEdit_9")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setEnabled(False)
        self.pushButton_19.setGeometry(QtCore.QRect(1160, 400, 111, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setEnabled(False)
        self.pushButton_20.setGeometry(QtCore.QRect(1160, 660, 111, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1100, 80, 48, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1100, 440, 48, 16))
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1100, 20, 191, 31))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(990, 30, 48, 16))
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1361, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setTitle("")
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOperational_Manual = QtWidgets.QAction(MainWindow)
        self.actionOperational_Manual.setObjectName("actionOperational_Manual")
        self.actions = QtWidgets.QAction(MainWindow)
        self.actions.setObjectName("actions")
        self.menu.addAction(self.actionAbout)
        self.menu.addAction(self.actionOperational_Manual)
        self.menu.addAction(self.actions)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_19.clicked['bool'].connect(self.textEdit_8.clear)
        self.pushButton_12.clicked['bool'].connect(self.textEdit_7.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机械臂上位机"))
        self.label.setText(_translate("MainWindow", "端口号："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.comboBox.setCurrentText(_translate("MainWindow", "9600"))
        self.comboBox.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox.setItemText(1, _translate("MainWindow", "300"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1200"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2400"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4800"))
        self.comboBox.setItemText(5, _translate("MainWindow", "19200"))
        self.comboBox.setItemText(6, _translate("MainWindow", "38400"))
        self.comboBox.setItemText(7, _translate("MainWindow", "57600"))
        self.comboBox.setItemText(8, _translate("MainWindow", "74880"))
        self.comboBox.setItemText(9, _translate("MainWindow", "115200"))
        self.comboBox.setItemText(10, _translate("MainWindow", "230400"))
        self.comboBox.setItemText(11, _translate("MainWindow", "250000"))
        self.pushButton.setText(_translate("MainWindow", "扫描"))
        self.pushButton_2.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_18.setText(_translate("MainWindow", "关闭串口"))
        self.groupBox_2.setTitle(_translate("MainWindow", "精确定位"))
        self.label_3.setText(_translate("MainWindow", "此区域按钮可控制各部分舵机每次运动一定角度"))
        self.label_4.setText(_translate("MainWindow", "底座舵机"))
        self.label_5.setText(_translate("MainWindow", "左舵机"))
        self.label_6.setText(_translate("MainWindow", "右舵机"))
        self.label_7.setText(_translate("MainWindow", "爪子舵机"))
        self.label_8.setText(_translate("MainWindow", "下部"))
        self.label_9.setText(_translate("MainWindow", "转盘"))
        self.groupBox_3.setTitle(_translate("MainWindow", "组合控制"))
        self.label_10.setText(_translate("MainWindow", "此区域按钮可启动各部位舵机进行一些组合运动"))
        self.pushButton_3.setText(_translate("MainWindow", "顺时针抓取"))
        self.pushButton_4.setText(_translate("MainWindow", "恢复初始设置"))
        self.pushButton_5.setText(_translate("MainWindow", "逆时针抓取"))
        self.pushButton_6.setText(_translate("MainWindow", "垂直直线平移"))
        self.pushButton_7.setText(_translate("MainWindow", "机械臂画方"))
        self.pushButton_8.setText(_translate("MainWindow", "自动模式"))
        self.pushButton_9.setText(_translate("MainWindow", "水平直线平移"))
        self.groupBox_4.setTitle(_translate("MainWindow", "组合动作"))
        self.pushButton_10.setText(_translate("MainWindow", "添加动作"))
        self.pushButton_11.setText(_translate("MainWindow", "删除动作"))
        self.pushButton_13.setText(_translate("MainWindow", "下载动作组"))
        self.pushButton_14.setText(_translate("MainWindow", "保存动作组"))
        self.pushButton_16.setText(_translate("MainWindow", "在线运行"))
        self.pushButton_17.setText(_translate("MainWindow", "运行下载动作组"))
        self.pushButton_12.setText(_translate("MainWindow", "清除"))
        self.pushButton_15.setText(_translate("MainWindow", "打开动作组"))
        self.pushButton_19.setText(_translate("MainWindow", "清除"))
        self.pushButton_20.setText(_translate("MainWindow", "发送"))
        self.label_12.setText(_translate("MainWindow", "接收区"))
        self.label_13.setText(_translate("MainWindow", "发送区"))
        self.label_11.setText(_translate("MainWindow", "Time"))
        self.label_14.setText(_translate("MainWindow", "Time:"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionAbout.setText(_translate("MainWindow", "关于我们"))
        self.actionOperational_Manual.setText(_translate("MainWindow", "操作手册"))
        self.actions.setText(_translate("MainWindow", "友情链接"))
